version: '3.8'

services:
  app:
    build:
      context: ./app  # FastAPI 프로젝트 디렉토리
    container_name: fastapi-app
    ports:
      - "8000:8000"  # FastAPI 서버 포트 매핑
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mysql
    volumes:
      - ./app:/app  # 로컬 코드 변경 사항을 컨테이너에 반영
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  data:
    driver: local