version: '3.8'

services:
  app:
    build:
      context: ./app  # FastAPI 프로젝트 디렉토리
    container_name: fastapi-app
    ports:
      - "8000:8000"  # FastAPI 서버 포트 매핑
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PYTHONPATH=/app
    depends_on:
      - mysql
    volumes:
      - ./app:/app  # 로컬 코드 변경 사항을 컨테이너에 반영
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"  # MySQL 포트 매핑
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - data:/var/lib/mysql  # 데이터 영구 저장

volumes:
  data:
    driver: local